_base_: '../_base_/cityscapes.yml'

batch_size: 16  # total: 4*4
iters: 100

optimizer:
  weight_decay: 5.0e-4

lr_scheduler:
  warmup_iters: 5
  warmup_start_lr: 1.0e-5
  learning_rate: 0.005

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 8192   # batch_size * 1024 * 512 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 8192
    - type: OhemCrossEntropyLoss
      min_kept: 8192
  coef: [1, 1, 1]

train_dataset:
  num_classes: 4
  transforms:
#    - type: ResizeStepScaling
#      min_scale_factor: 0.125
#      max_scale_factor: 1.5
#      scale_step_size: 0.125
#    - type: RandomPaddingCrop
#      crop_size: [512, 256]
    - type: Resize
      target_size: [512,256]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.5
#      contrast_range: 0.5
#      saturation_range: 0.5
    - type: Normalize
  mode: train

val_dataset:
  num_classes: 4

test_config:
  aug_eval: True
  scales: 0.5

model:
  type: PPLiteSeg
  num_classes: 4
  backbone:
    type: STDC1
    pretrained:
  arm_out_chs: [32, 64, 128]
  seg_head_inter_chs: [32, 64, 64]
